"use client";

import React, { useState } from "react";
import {
  Sparkles,
  ChevronDown,
  ChevronUp,
  CheckCircle2,
  Lightbulb,
  ArrowRight,
  FileText,
} from "lucide-react";

export interface VoiceSummary {
  summary: string;
  takeaways: string[];
  tasks: string[];
  recommendations: string[];
  nextActions: string[];
}

interface VoiceSummaryCardProps {
  summary: VoiceSummary;
  sessionDate: string;
}

interface SectionProps {
  icon: React.ElementType;
  title: string;
  items: string[];
  iconColor: string;
  dotColor: string;
}

function SummarySection({ icon: Icon, title, items, iconColor, dotColor }: SectionProps) {
  return (
    <div>
      <div className="flex items-center gap-2 mb-2">
        <Icon className={`w-3.5 h-3.5 ${iconColor}`} />
        <p className="text-[10px] font-semibold uppercase tracking-widest text-[#A0AEC0]">
          {title}
        </p>
      </div>
      <ul className="space-y-1.5">
        {items.map((item, i) => (
          <li key={i} className="flex items-start gap-2 text-sm text-[#4A5568] leading-relaxed">
            <span className={`w-1.5 h-1.5 rounded-full ${dotColor} mt-1.5 flex-shrink-0`} />
            {item}
          </li>
        ))}
      </ul>
    </div>
  );
}

export default function VoiceSummaryCard({ summary, sessionDate }: VoiceSummaryCardProps) {
  const [expanded, setExpanded] = useState(true);

  return (
    <div className="bg-white border border-[#E8E8E4] rounded-2xl overflow-hidden mb-6">
      {/* Header */}
      <button
        onClick={() => setExpanded((v) => !v)}
        className="w-full flex items-center justify-between px-4 lg:px-5 py-4 hover:bg-[#FAFAF8] transition-colors"
      >
        <div className="flex items-center gap-2.5">
          <div className="w-8 h-8 rounded-xl bg-[#FFF0E6] border border-[#F4C9A4] flex items-center justify-center">
            <Sparkles className="w-4 h-4 text-[#E85D04]" />
          </div>
          <div className="text-left">
            <p className="text-sm font-bold text-[#1A1A1A]">Session Summary</p>
            <p className="text-[10px] text-[#A0AEC0]">Generated by Tenda AI · {sessionDate}</p>
          </div>
        </div>
        {expanded ? (
          <ChevronUp className="w-4 h-4 text-[#A0AEC0]" />
        ) : (
          <ChevronDown className="w-4 h-4 text-[#A0AEC0]" />
        )}
      </button>

      {expanded && (
        <div className="px-4 lg:px-5 pb-5 space-y-5 border-t border-[#F0F0EC] pt-4">
          {/* Summary paragraph */}
          <div className="bg-[#FAFAF8] border border-[#E8E8E4] rounded-xl p-3">
            <div className="flex items-center gap-1.5 mb-2">
              <FileText className="w-3.5 h-3.5 text-[#A0AEC0]" />
              <p className="text-[10px] font-semibold uppercase tracking-widest text-[#A0AEC0]">
                Overview
              </p>
            </div>
            <p className="text-sm text-[#4A5568] leading-relaxed">{summary.summary}</p>
          </div>

          {/* Sections grid */}
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <SummarySection
              icon={Lightbulb}
              title="Key takeaways"
              items={summary.takeaways}
              iconColor="text-amber-500"
              dotColor="bg-amber-400"
            />
            <SummarySection
              icon={CheckCircle2}
              title="Tasks identified"
              items={summary.tasks}
              iconColor="text-green-500"
              dotColor="bg-green-400"
            />
            <SummarySection
              icon={Sparkles}
              title="Recommendations"
              items={summary.recommendations}
              iconColor="text-[#E85D04]"
              dotColor="bg-[#E85D04]"
            />
            <SummarySection
              icon={ArrowRight}
              title="Next actions"
              items={summary.nextActions}
              iconColor="text-blue-500"
              dotColor="bg-blue-400"
            />
          </div>

          {/* Export action */}
          <div className="pt-2 flex items-center gap-2">
            <button className="flex items-center gap-1.5 text-xs font-semibold text-[#E85D04] hover:gap-2 transition-all">
              Export summary
              <ArrowRight className="w-3.5 h-3.5" />
            </button>
            <span className="text-[#E8E8E4]">·</span>
            <button className="text-xs font-semibold text-[#A0AEC0] hover:text-[#4A5568] transition-colors">
              Add to notes
            </button>
          </div>
        </div>
      )}
    </div>
  );
}
